# Generated by Django 6.0.4 on 2026-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_blog_id_af747d_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='blog',
            new_name='blogId',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blogId', '-timestamp'], name='posts_post_blogId__c0a753_idx'),
        ),
    ]
