# Generated by Django 6.0.4 on 2026-05-17 17:42

import django.db.models.deletion
from django.db import migrations, models


def copy_media_to_assets(apps, schema_editor):
    PostsMedia = apps.get_model('posts', 'Media')
    AssetsMedia = apps.get_model('assets', 'Media')
    db_alias = schema_editor.connection.alias

    for media in PostsMedia.objects.using(db_alias).all():
        AssetsMedia.objects.using(db_alias).update_or_create(
            id=media.id,
            defaults={
                'url': media.url,
                'type': media.type,
                'width': media.width,
                'height': media.height,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('posts', '0002_alter_media_id'),
    ]

    operations = [
        migrations.RunPython(copy_media_to_assets, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='postcontent',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.media'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
