# Generated by Django 6.0.4 on 2026-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcontent_media_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='layout',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
