# Generated by Django 6.0.4 on 2026-05-30 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_bookmark_eventcomment_postcomment_and_more'),
        ('profiles', '0007_profile_last_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_interactions', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed'], name='interaction_process_a347a0_idx'), models.Index(fields=['profile', 'processed'], name='interaction_profile_b6645b_idx')],
            },
        ),
    ]
