"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'posts',
    'rest_framework',
    'profiles',
    'interactions',
    'events',
    'assets',
    "relationships",
    'drf_spectacular', # Añade esto
    'django.contrib.sites',  # Obligatorio para allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Para Google
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework.authtoken',
    'django.contrib.gis',  # <- Añade esto
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Añade esta línea exactamente así:
    'allauth.account.middleware.AccountMiddleware',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#ROOT_URLCONF = 'core.urls'
#WSGI_APPLICATION = 'core.wsgi.application'
ROOT_URLCONF = 'loom.urls'
WSGI_APPLICATION = 'loom.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # <- Motor GeoDjango#'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.User'  # Indica que usaremos nuestro modelo de usuario personalizado

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    # ...
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # Esto protege TODO por defecto
    ),
}

REST_AUTH = {
    #'USE_JWT': True, # Esto es clave: usa JWT en lugar de tokens opacos
    #'JWT_AUTH_COOKIE': 'my-app-auth',
    #'JWT_AUTH_HTTPONLY': False, # Permite que el refresh token sea accesible por JS
    #'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-token',
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,  # Si no usas cookies, esto no tiene efecto, pero es bueno dejarlo por si acaso.
    # Desactivamos el manejo de cookies para que los tokens siempre vengan en el body.
    'JWT_AUTH_COOKIE': None,
    'JWT_AUTH_REFRESH_COOKIE': None,
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.UserSerializer',
    'LOGIN_SERIALIZER': 'accounts.serializers.LoginSerializer',
    'REGISTER_SERIALIZER': 'accounts.serializers.RegisterSerializer', # Add this line
    'JWT_SERIALIZER': 'dj_rest_auth.serializers.JWTSerializer', # ¡Esta es la clave para el refresh token!

}

# Configuración de allauth
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# (Opcional) Configuración básica de tu API
SPECTACULAR_SETTINGS = {
    'TITLE': 'Mi API de Usuarios',
    'DESCRIPTION': 'Documentación de endpoints de mi proyecto',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Enviar los correos a la consola en lugar de intentar conectar a SMTP
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Opcional: Si quieres desactivar la verificación por email para probar rápido
# (Esto hará que el usuario quede verificado automáticamente al registrarse)
ACCOUNT_EMAIL_VERIFICATION = 'none'

# --- Logging Configuration ---
# Esto es clave para ver los logs de nivel INFO en la consola de Docker.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO', # Captura desde el nivel INFO hacia arriba.
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Puedes cambiarlo a 'DEBUG' para ver aún más detalle.
            'propagate': True,
        },
    },
}

# Configuración de Allauth para usar email como método de login principal
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# 1. Ruta base de tu entorno Conda
CONDAS_ENV_PATH = r"C:\Users\Aldair\miniconda3\envs\geomatico"
BIN_PATH = os.path.join(CONDAS_ENV_PATH, "Library", "bin")

# Si estás en Windows (Desarrollo local con Conda)
if os.name == "nt":
    CONDAS_ENV_PATH = r"C:\Users\Aldair\miniconda3\envs\geomatico"
    BIN_PATH = os.path.join(CONDAS_ENV_PATH, "Library", "bin")

    if sys.version_info >= (3, 8):
        os.add_dll_directory(BIN_PATH)

    GDAL_LIBRARY_PATH = os.path.join(BIN_PATH, "gdal.dll")
    GEOS_LIBRARY_PATH = os.path.join(BIN_PATH, "geos_c.dll")