# Generated by Django 6.0.4 on 2026-05-05 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_alter_media_id'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the event.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title. Auto-generated if left blank.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event.', null=True)),
                ('start_time', models.DateTimeField(help_text='When the event starts.')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the event ends (optional).', null=True)),
                ('location_name', models.CharField(blank=True, help_text="Name of the location (e.g., 'Online', 'Central Park Cafe').", max_length=255, null=True)),
                ('location_address', models.CharField(blank=True, help_text='Physical address or URL for online events.', max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geographical location.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geographical location.', max_digits=9, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees allowed (optional).', null=True)),
                ('is_online', models.BooleanField(default=False, help_text='True if the event is online, False if physical.')),
                ('is_public', models.BooleanField(default=True, help_text='True if the event is publicly visible, False for private events.')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if the event has been cancelled (soft delete).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', help_text='Current status of the event.', max_length=20)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the event.', null=True, upload_to='event_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The profile that created this event.', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='profiles.profile')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorization and discoverability.', related_name='events', to='posts.tag')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'status'], name='events_even_start_t_ade85e_idx'), models.Index(fields=['creator', 'start_time'], name='events_even_creator_bbe5ef_idx')],
            },
        ),
    ]
