# Generated by Django 6.0.4 on 2026-05-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
    ]
