# Generated by Django 6.0.4 on 2026-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('events', '0002_remove_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Associated media assets for the event.', related_name='events', to='assets.media'),
        ),
    ]
