# Generated by Django 6.0.4 on 2026-05-18 02:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Localización del evento en formato (Longitud, Latitud) usando WGS84.', null=True, srid=4326),
        ),
    ]
