# Generated by Django 6.0.4 on 2026-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_latitude_remove_event_longitude_and_more'),
        ('profiles', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text="Profiles that have RSVP'd to this event.", related_name='attending_events', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('sports', 'Sports'), ('arts', 'Arts'), ('music', 'Music'), ('food', 'Food'), ('other', 'Other')], default='other', help_text='Category of the event.', max_length=20),
        ),
    ]
