# Generated by Django 6.0.4 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_attendees_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', help_text='Current status of the event.', max_length=20),
        ),
    ]
