# Generated by Django 6.0.5 on 2026-06-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_slug_and_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('science', 'Science & Research'), ('technology', 'Technology & Innovation'), ('ai', 'Artificial Intelligence'), ('data', 'Data Science & Analytics'), ('cybersecurity', 'Cybersecurity'), ('engineering', 'Engineering'), ('education', 'Education & Learning'), ('workshops', 'Workshops & Training'), ('career', 'Career Development'), ('business', 'Business & Entrepreneurship'), ('startups', 'Startups & Venture Capital'), ('marketing', 'Marketing & Advertising'), ('sales', 'Sales & Networking'), ('finance', 'Finance & Investing'), ('real_estate', 'Real Estate'), ('arts', 'Arts & Culture'), ('music', 'Music & Concerts'), ('theater', 'Theater & Performing Arts'), ('dance', 'Dance'), ('film', 'Film, Media & Photography'), ('literature', 'Literature & Books'), ('museums', 'Museums & Exhibitions'), ('fashion', 'Fashion & Design'), ('crafts', 'Crafts & Handmade'), ('gaming', 'Gaming & Esports'), ('comedy', 'Comedy & Stand-up'), ('nightlife', 'Nightlife & Parties'), ('festivals', 'Festivals'), ('conventions', 'Conventions & Expos'), ('sports', 'Sports'), ('fitness', 'Fitness & Gym'), ('running', 'Running & Marathons'), ('cycling', 'Cycling'), ('yoga', 'Yoga & Meditation'), ('martial_arts', 'Martial Arts'), ('water_sports', 'Water Sports'), ('outdoor', 'Outdoor & Adventure'), ('hiking', 'Hiking & Trekking'), ('camping', 'Camping'), ('nature', 'Nature & Wildlife'), ('environment', 'Environment & Sustainability'), ('food', 'Food & Drink'), ('wine', 'Wine Tasting'), ('beer', 'Beer & Craft Brewing'), ('coffee', 'Coffee & Specialty Drinks'), ('cooking', 'Cooking Classes'), ('health', 'Health & Wellness'), ('mental_health', 'Mental Health'), ('wellness', 'Wellness & Self-care'), ('beauty', 'Beauty & Personal Care'), ('community', 'Community & Social'), ('networking', 'Networking'), ('charity', 'Charity & Volunteering'), ('religion', 'Religion & Spirituality'), ('politics', 'Politics & Civic Engagement'), ('lgbtq', 'LGBTQ+'), ('women', 'Women-focused Events'), ('seniors', 'Senior Activities'), ('family', 'Family & Kids'), ('kids', 'Kids Activities'), ('parenting', 'Parenting'), ('travel', 'Travel & Tourism'), ('luxury', 'Luxury Lifestyle'), ('shopping', 'Shopping & Markets'), ('pets', 'Pets & Animals'), ('automotive', 'Cars & Automotive'), ('conference', 'Conferences'), ('seminar', 'Seminars'), ('meetup', 'Meetups'), ('exhibition', 'Exhibitions'), ('competition', 'Competitions'), ('awards', 'Awards & Ceremonies'), ('fundraiser', 'Fundraisers'), ('other', 'Other')], default='other', help_text='Category of the event.', max_length=20),
        ),
    ]
