# Generated by Django 6.0.5 on 2026-06-03 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_event_extra_urls_and_requirements'),
        ('profiles', '0007_profile_last_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secure_attendance_token', models.CharField(help_text='Secure unique token for this specific user and event attendance.', max_length=255, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Timestamp when the attendee was checked in.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='profiles.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
