# Generated by Django 6.0.4 on 2026-05-18 01:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Última localización conocida del perfil en formato (Longitud, Latitud) usando WGS84.', null=True, srid=4326),
        ),
    ]
