# Generated by Django 6.0.4 on 2026-05-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcontent_media_delete_media'),
        ('profiles', '0005_alter_profile_unique_together_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags que este perfil sigue.', related_name='followers', to='posts.tag'),
        ),
    ]
