# Generated by Django 6.0.4 on 2026-05-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_followed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último post creado por este perfil.', null=True),
        ),
    ]
