# Generated by Django 6.0.4 on 2026-05-17 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('video/mp4', 'MP4 Video'), ('video/webm', 'WebM Video'), ('audio/mpeg', 'MP3 Audio')], max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
    ]
