# Generated by Django 6.0.5 on 2026-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_86ea8b_idx',
            old_name='notifications_notification_recipient_is_read_created_at',
        ),
    ]
