# Generated by Django 6.0.5 on 2026-06-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_userdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='notificatio_account_d2182b_idx',
            old_name='notifications_account_is_active_idx',
        ),
    ]
